version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    env_file: .env
    networks:
      - backend

  postgres:
    container_name: db
    image: postgres
    restart: always
    env_file: .env
    volumes:
      - postgres:/data/postgres
    networks:
      - backend

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8081:80"
    networks:
      - frontend

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

volumes:
  postgres:

networks:
  backend:
  frontend:
