version: '3.9'

services:
  backend:
    container_name: backend
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "4000:3000"
    env_file: .env

  postgres:
    container_name: db
    image: postgres
    restart: always
    env_file: .env

  frontend:
    container_name: frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:3000"

  adminer:
    image: adminer
    restart: always
    ports:
      - "8081:8080"
